### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>

### ISSUE THREAD

**Issue by jamfly** [xinjli/allosaurus#22]
Hi:

It seems like your pre-trained model link is dead

```
from:  https://www.pyspeech.com/static/model/recognition/allosaurus/latest.tar.gz
to:    /python_path/lib/python3.7/site-packages/allosaurus-0.4.2-py3.7.egg/allosaurus/pretrained
please wait...
Error: could not download the model
Traceback (most recent call last):
  File "/python_path/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/python_path/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/python_path/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/python_path/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/python_path/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/python_path/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/python_path/lib/python3.7/http/client.py", line 1439, in connect
    super().connect()
  File "/python_path/lib/python3.7/http/client.py", line 944, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/python_path/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/python_path/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out
```

my python version: `3.7.9`
allosaurus version: commit `a11771dd4aa16b5162e9aae6238a58bbcac430e5`

**Comment by xinjli** [comment]
Hi, 

The link is working on my machine,  can you try downloading again?
If it still does not work, can you tell me your DNS results?

``` bash
nslookup www.pyspeech.com
```

**Comment by jamfly** [comment]
Hi:

here is my DNS information

```
Server:		140.109.20.250
Address:	140.109.20.250#53

Non-authoritative answer:
Name:	www.pyspeech.com
Address: 128.2.205.47
```

**Comment by xinjli** [comment]
The last IP address is the correct one, I am not sure why you cannot download it.

Is it possible that you can download the model directly from your browser?
https://www.pyspeech.com/static/model/recognition/allosaurus/latest.tar.gz

**Comment by jamfly** [comment]
I've tried to download it from browser, curl, and wget.
None of them are working...

**Comment by xinjli** [comment]
hmm, it's super weird...
It is hosted from machines from Carnegie Mellon. Unless you are not blocked by cmu domain, I have no idea why you cannot access it...

Can you send me an email, so I can directly share the model with you?
xinjianl (@) cs.cmu.edu
