### ISSUE TITLE
Checking the full language list raised IndexError

### ISSUE THREAD

**Issue by yistLin** [xinjli/allosaurus#25]
While I'm checking the full language list with `python -m allosaurus.bin.list_lan`, the executable raised **IndexError**. The following is the error message:
```text
Traceback (most recent call last):
  File "/home/yist/.pyenv/versions/3.8.5/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yist/.pyenv/versions/3.8.5/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yist/.pyenv/versions/3.8.5/lib/python3.8/site-packages/allosaurus/bin/list_lang.py", line 13, in <module>
    model_path = get_model_path(args.model)
  File "/home/yist/.pyenv/versions/3.8.5/lib/python3.8/site-packages/allosaurus/model.py", line 27, in get_model_path
    resolved_model_name = resolve_model_name(model_name)
  File "/home/yist/.pyenv/versions/3.8.5/lib/python3.8/site-packages/allosaurus/model.py", line 76, in resolve_model_name
    return models[0].name
IndexError: list index out of range
```

**Comment by yistLin** [comment]
But right after I downloaded the pretrained models, it works just fine.

**Comment by xinjli** [comment]
Hi, thanks for reporting this.
We will fix it to download the model if not exists.

Thanks!
