### ISSUE TITLE
Unable to run interspeech21 model

### ISSUE THREAD

**Issue by SlistInc** [xinjli/allosaurus#63]
When trying to run the interspeech model I encounter an error. This is the sequence I run to encounter the error:

```
(tensorflow_m1) My-MBP:JupyterNotebooks myusername$ pip install git+https://github.com/xinjli/allosaurus.git@interspeech21
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting git+https://github.com/xinjli/allosaurus.git@interspeech21
  Cloning https://github.com/xinjli/allosaurus.git (to revision interspeech21) to /private/var/folders/2d/km5m64ts3zd3vyvm0qm8t_zm0000gn/T/pip-req-build-w08ikbza
  Running command git clone --filter=blob:none --quiet https://github.com/xinjli/allosaurus.git /private/var/folders/2d/km5m64ts3zd3vyvm0qm8t_zm0000gn/T/pip-req-build-w08ikbza
  Running command git checkout -b interspeech21 --track origin/interspeech21
  Switched to a new branch 'interspeech21'
  Branch 'interspeech21' set up to track remote branch 'interspeech21' from 'origin'.
  Resolved https://github.com/xinjli/allosaurus.git to commit eb77df8fe9b5acb5578fa0bf46e68f2088d57fd4
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scipy in /opt/homebrew/lib/python3.9/site-packages (from allosaurus==1.0.2) (1.8.0)
Requirement already satisfied: numpy in /opt/homebrew/lib/python3.9/site-packages (from allosaurus==1.0.2) (1.21.5)
Requirement already satisfied: resampy in /opt/homebrew/lib/python3.9/site-packages (from allosaurus==1.0.2) (0.2.2)
Requirement already satisfied: panphon in /opt/homebrew/lib/python3.9/site-packages (from allosaurus==1.0.2) (0.20.0)
Requirement already satisfied: torch in /opt/homebrew/lib/python3.9/site-packages (from allosaurus==1.0.2) (1.10.2)
Requirement already satisfied: editdistance in /opt/homebrew/lib/python3.9/site-packages (from allosaurus==1.0.2) (0.6.0)
Requirement already satisfied: PyYAML in /opt/homebrew/lib/python3.9/site-packages (from panphon->allosaurus==1.0.2) (6.0)
Requirement already satisfied: setuptools in /opt/homebrew/lib/python3.9/site-packages (from panphon->allosaurus==1.0.2) (60.5.0)
Requirement already satisfied: unicodecsv in /opt/homebrew/lib/python3.9/site-packages (from panphon->allosaurus==1.0.2) (0.14.1)
Requirement already satisfied: munkres in /opt/homebrew/lib/python3.9/site-packages (from panphon->allosaurus==1.0.2) (1.1.4)
Requirement already satisfied: regex in /opt/homebrew/lib/python3.9/site-packages (from panphon->allosaurus==1.0.2) (2021.11.10)
Requirement already satisfied: numba>=0.32 in /opt/homebrew/lib/python3.9/site-packages (from resampy->allosaurus==1.0.2) (0.55.2)
Requirement already satisfied: six>=1.3 in /opt/homebrew/lib/python3.9/site-packages (from resampy->allosaurus==1.0.2) (1.15.0)
Requirement already satisfied: typing-extensions in /opt/homebrew/lib/python3.9/site-packages (from torch->allosaurus==1.0.2) (4.0.1)
Requirement already satisfied: llvmlite<0.39,>=0.38.0rc1 in /opt/homebrew/lib/python3.9/site-packages (from numba>=0.32->resampy->allosaurus==1.0.2) (0.38.1)
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
WARNING: You are using pip version 22.0.3; however, version 22.1.2 is available.
You should consider upgrading via the '/opt/homebrew/opt/python@3.9/bin/python3.9 -m pip install --upgrade pip' command.
```

```
(tensorflow_m1) My-MBP:JupyterNotebooks myusername$ python -m allosaurus.bin.download_model -m interspeech21
downloading model  interspeech21
from:  https://github.com/xinjli/allosaurus/releases/download/v1.0/interspeech21.tar.gz
to:    /Users/myusername/miniforge3/envs/tensorflow_m1/lib/python3.9/site-packages/allosaurus/pretrained
please wait...
```

```
(tensorflow_m1) My-MBP:JupyterNotebooks myusername$ python -m allosaurus.run --timestamp=True -i sample.wav -m interspeech21
Traceback (most recent call last):
  File "/Users/myusername/miniforge3/envs/tensorflow_m1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/myusername/miniforge3/envs/tensorflow_m1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/myusername/miniforge3/envs/tensorflow_m1/lib/python3.9/site-packages/allosaurus/run.py", line 36, in <module>
    recognizer = read_recognizer(args)
  File "/Users/myusername/miniforge3/envs/tensorflow_m1/lib/python3.9/site-packages/allosaurus/app.py", line 38, in read_recognizer
    pm = read_pm(model_path, inference_config)
  File "/Users/myusername/miniforge3/envs/tensorflow_m1/lib/python3.9/site-packages/allosaurus/pm/factory.py", line 13, in read_pm
    pm_config = Namespace(**json.load(open(str(model_path / 'pm_config.json'))))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/myusername/miniforge3/envs/tensorflow_m1/lib/python3.9/site-packages/allosaurus/pretrained/interspeech21/pm_config.json'
```

Please consider that I am encountering the same problem when installing allosaurus from the interspeech branch or the regular allosaurus.

Is anyone else encountering this problem or found a solution?

**Comment by mo-othman** [comment]
I'm having the same issue, have you found a solution?
